export declare const drawOptions: {
    color: string;
    labelColor: string;
    shadowColor: string;
    font: string;
    lineHeight: number;
    lineWidth: number;
    pointSize: number;
    roundRect: number;
    drawPoints: Boolean;
    drawLabels: Boolean;
    drawBoxes: Boolean;
    drawPolygons: Boolean;
    fillPolygons: Boolean;
    useDepth: Boolean;
    useCurves: Boolean;
    bufferedOutput: Boolean;
    useRawBoxes: Boolean;
};
export declare function gesture(inCanvas: any, result: any): Promise<void>;
export declare function face(inCanvas: any, result: any): Promise<void>;
export declare function body(inCanvas: any, result: any): Promise<void>;
export declare function hand(inCanvas: any, result: any): Promise<void>;
export declare function object(inCanvas: any, result: any): Promise<void>;
export declare function canvas(inCanvas: any, outCanvas: any): Promise<void>;
export declare function all(inCanvas: any, result: any): Promise<void>;
