export declare const MESH_ANNOTATIONS: {
    silhouette: number[];
    lipsUpperOuter: number[];
    lipsLowerOuter: number[];
    lipsUpperInner: number[];
    lipsLowerInner: number[];
    rightEyeUpper0: number[];
    rightEyeLower0: number[];
    rightEyeUpper1: number[];
    rightEyeLower1: number[];
    rightEyeUpper2: number[];
    rightEyeLower2: number[];
    rightEyeLower3: number[];
    rightEyebrowUpper: number[];
    rightEyebrowLower: number[];
    rightEyeIris: number[];
    leftEyeUpper0: number[];
    leftEyeLower0: number[];
    leftEyeUpper1: number[];
    leftEyeLower1: number[];
    leftEyeUpper2: number[];
    leftEyeLower2: number[];
    leftEyeLower3: number[];
    leftEyebrowUpper: number[];
    leftEyebrowLower: number[];
    leftEyeIris: number[];
    midwayBetweenEyes: number[];
    noseTip: number[];
    noseBottom: number[];
    noseRightCorner: number[];
    noseLeftCorner: number[];
    rightCheek: number[];
    leftCheek: number[];
};
export declare const MESH_TO_IRIS_INDICES_MAP: {
    key: string;
    indices: number[];
}[];
export declare const UV468: number[][];
export declare const TRI468: number[];
export declare const TRI68: number[];
export declare const TRI33: number[];
export declare const TRI7: number[];
export declare const VTX68: number[];
export declare const VTX33: number[];
export declare const VTX7: number[];
export declare const UV68: number[][];
export declare const UV33: number[][];
export declare const UV7: number[][];
//# sourceMappingURL=coords.d.ts.map