export declare const drawOptions: {
    color: string;
    labelColor: string;
    shadowColor: string;
    font: string;
    lineHeight: number;
    lineWidth: number;
    pointSize: number;
    roundRect: number;
    drawPoints: Boolean;
    drawLabels: Boolean;
    drawBoxes: Boolean;
    drawPolygons: Boolean;
    fillPolygons: Boolean;
    useDepth: Boolean;
    useCurves: Boolean;
    bufferedOutput: Boolean;
    useRawBoxes: Boolean;
};
export declare function gesture(inCanvas: HTMLCanvasElement, result: Array<any>): Promise<void>;
export declare function face(inCanvas: HTMLCanvasElement, result: Array<any>): Promise<void>;
export declare function body(inCanvas: HTMLCanvasElement, result: Array<any>): Promise<void>;
export declare function hand(inCanvas: HTMLCanvasElement, result: Array<any>): Promise<void>;
export declare function object(inCanvas: HTMLCanvasElement, result: Array<any>): Promise<void>;
export declare function canvas(inCanvas: HTMLCanvasElement, outCanvas: HTMLCanvasElement): Promise<void>;
export declare function all(inCanvas: HTMLCanvasElement, result: any): Promise<void>;
